vich_uploader:
    db_driver: orm

    mappings:
        manga_thumb:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        manga_images:
            uri_prefix: /images/mangas
            upload_destination: '%kernel.project_dir%/public/images/mangas'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
