#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

mangas_list:
  path: /mangas_list
  controller: App\Controller\MangasController::list
